### ISSUE TITLE
Enable php5.6 in Ubuntu16.04

### ISSUE THREAD

**Issue by zabudskyi** [sous-chefs/apache2#528] opened 2018-03-20 13:00 UTC
### Cookbook version
5.0.1

### Chef-client version
13.8.5

### Platform Details
Ubuntu 16.04

### Scenario:
Enable php5.6 module in Ubuntu 16.04

### Steps to Reproduce:
My recipe
```
include_recipe 'apache2'
include_recipe 'apache2::mod_php'

apt_repository 'ondrejphp' do
  uri          'ppa:ondrej/php'
end

package 'libapache2-mod-php5.6' do
  action :install
end

apache_module "php" do
  conf true
  filename "libphp5.6.so"
end

apache_module "php7.0" do
  conf false
end
```
### Expected Result:
php5.6 module to be enabled and php7.0 to be disabled
### Actual Result:
```
 * template[/etc/apache2/mods-available/php.conf] action create
    
    ================================================================================
    Error executing action `create` on resource 'template[/etc/apache2/mods-available/php.conf]'
    ================================================================================
    
    Chef::Exceptions::FileNotFound
    ------------------------------
    Cookbook 'api16' (2.0.0) does not contain a file at any of these locations:
      templates/ubuntu-16.04/mods/php.conf.erb
      templates/ubuntu/mods/php.conf.erb
      templates/default/mods/php.conf.erb
      templates/mods/php.conf.erb
    
    This cookbook _does_ contain: ['templates/default/apache-api.conf.erb','templates/default/db.php.erb','templates/default/certificate.erb','templates/default/htpasswd.erb','templates/default/nginx-api-default.conf.erb','templates/default/nginx-backend.conf.erb','templates/default/nginx-api.conf.erb','templates/default/php5.ini','templates/default/phpfpm.erb','templates/default/private_key.erb','templates/default/set_environment.php.erb','templates/default/php7.ini','templates/default/nginx-api-vpnsupportcenter.conf.erb','templates/default/ssh_wrapper.sh.erb','templates/default/nginx-api-default-ssl.conf.erb','templates/default/nginx-api-vpnsupportcenter-ssl.conf.erb','templates/default/config.yml.erb','templates/default/htaccess.erb']
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/apache2/definitions/apache_mod.rb
    
     23:   template "#{node['apache']['dir']}/mods-available/#{params[:name]}.conf" do
     24:     source "mods/#{params[:name]}.conf.erb"
     25:     mode '0644'
     26:     notifies :reload, 'service[apache2]', :delayed
     27:   end
     28: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/apache2/definitions/apache_mod.rb:23:in `block in from_file'
    
    template("/etc/apache2/mods-available/php.conf") do
      params {:name=>"php"}
      action [:create]
      default_guard_interpreter :default
      source "mods/php.conf.erb"
      declared_type :template
      cookbook_name "api16"
      recipe_name "install"
      owner nil
      group nil
      mode "0644"
      path "/etc/apache2/mods-available/php.conf"
      verifications []
    end
```
Why am I getting this error? 
` templates/mods/php.conf.erb` file exists

**Comment by josephholsten** [comment] 2018-11-26 20:18
@zabudskyi how's it going reproducing this? do you need any help? I'll be closing this ticket in a week if you aren't seeing the issue any longer.

**Comment by damacus** [comment] 2019-02-20 20:39
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Closed by damacus** 2019-02-20 20:39 UTC
Labels: Status: Pending Contributor, Type: Bug
