### ISSUE TITLE
Service name is not defined correctly

### ISSUE THREAD

**Issue by emillbrandt** [sous-chefs/apache2#603] opened 2019-02-26 00:45 UTC
# Brief Description

This is a regression in v6.0.0
           
           Error executing action `enable` on resource 'apache2_module[proxy]'
           
           Chef::Exceptions::ResourceNotFound
           ----------------------------------
           resource execute[a2enmod proxy] is configured to notify resource service[apache2] with action reload,
           but service[apache2] cannot be found in the resource collection. execute[a2enmod proxy] is defined in
           /tmp/kitchen/cache/cookbooks/apache2/resources/module.rb:33:in `block in class_from_file'

I traced the issue to the service being [created](https://github.com/sous-chefs/apache2/blob/master/resources/install.rb#L333), however when other resources refer to the service [resource](https://github.com/sous-chefs/apache2/blob/master/resources/module.rb#L59) in a recipe the resource cannot be found.  

## Cookbook version

6.0.0

## Chef-client version

14.8.12

## Platform Details

centos 7 in vagrant

## Scenario

Use any resource

**Comment by emillbrandt** [comment] 2019-02-26 00:47
I may be able to submit a PR later this week.

**Comment by emillbrandt** [comment] 2019-02-26 03:03
I suppose adding my cookbook example would be a good idea.

```
include_recipe 'apache2'
include_recipe 'apache2::mod_proxy_http'
include_recipe 'apache2::mod_ssl'

apache2_default_site 'ssl_redirect' do
  port '80'
  template_source 'ssl_redirect.conf.erb'
  action :enable
end

apache2_site 'ssl_redirect' do
  action :enable
end

apache2_default_site 'opennms' do
  port '443'
  template_source 'opennms.conf.erb'
  action :enable
end

apache2_site 'opennms' do
  action :enable
end

selinux_policy_boolean 'httpd_can_network_connect' do
  value true
end
```

**Comment by damacus** [comment] 2019-02-26 07:57
Hey,

thanks for filling an issue! 

A side note to this issue why are you mixing installing with a recipe and resources? A PR here would be great 

In the test recipes we get around not being able to find a resource within a resource, by adding a service resource within the test cookbook [see here for an example](https://github.com/sous-chefs/apache2/blob/master/test/cookbooks/test/recipes/default.rb#L13-L18)

**Comment by bottkv488** [comment] 2019-02-28 12:22
@damacus ,
IMO this is a duplicate of https://github.com/sous-chefs/apache2/issues/598
which has been fixed by https://github.com/sous-chefs/apache2/pull/599

**Comment by rtheobald** [comment] 2019-02-28 20:25
This is also happening with my Debian (Ubuntu) platform.

**Comment by emillbrandt** [comment] 2019-02-28 20:29
Yeah, I mischaracterized the issue.  The issue is that `service[apache2]` is inaccessible when called from other resources.  I'll clean up my description.

**Comment by emillbrandt** [comment] 2019-02-28 20:36
The reason recipes and resources were being mixed was because I was in the middle of upgrading my cookbook from v5 and guidance in `UPGRADING.md` is a little sparse.  I have since just changed those to resources.

**Comment by damacus** [comment] 2019-03-04 15:44
@emillbrandt if you have some feedback for more information to put into the UPGRADING.MD I would love to hear it! :)

**Comment by Xorima** [comment] 2019-03-20 17:26
Hi, 

as version 7.0.0 has been released could you let us know if this is still an issue please?

Thanks

**Comment by timcase** [comment] 2019-03-23 20:50
Can confirm this is still an issue in 7.0.0
```

Chef::Exceptions::ResourceNotFound
----------------------------------
resource execute[a2enmod ssl] is configured to notify resource service[apache2] 
with action reload, but service[apache2] cannot be found in the resource collection. 
execute[a2enmod ssl] is defined in 
/var/chef/cache/cookbooks/apache2/resources/module.rb:41:in `block in class_from_file'

```

**Comment by damacus** [comment] 2019-03-25 08:04
@timcase did you specify a service resource like the test cookbooks?

**Comment by damacus** [comment] 2019-05-09 20:19
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Closed by damacus** 2019-05-09 20:19 UTC
