### ISSUE TITLE
Unable to reload httpd service

### ISSUE THREAD

**Issue by lily-liu** [sous-chefs/apache2#553] opened 2018-08-29 03:08 UTC
### Cookbook version
5.2.0

### Chef-client version
14.2.0

### Platform Details
Amazon Linux 2 - 2.0.20180810 running on c4.xlarge instance.

### Scenario:
Using chef to provision dependencies and libraries before creating an AMI using packer.

### Steps to Reproduce:
1. Include apache2 cookbook on our cookbook.
2. Run automation script to provision the instance using our cookbook.

### Expected Result:
AMI creation process succeded.

### Actual Result:
AMI creation process failed due to reload action fails.
Also, we notice that restart action is running without any problem.
On the instance, reload process failed at graceful stop, so the httpd process isn't terminated

The snippets of our cookbook
[snippets.zip](https://github.com/sous-chefs/apache2/files/2330526/snippets.zip)

Packer's error log
[error.txt](https://github.com/sous-chefs/apache2/files/2330534/error.txt)

**Comment by damacus** [comment] 2018-09-05 08:32
Are you able to replicate this outside Packer with the same configuration?

Can you also post the apache2 config here rather than a zip please?

**Comment by lily-liu** [comment] 2018-09-05 11:10
> **Are you able to replicate this outside Packer with the same configuration?**


not yet - i am comparing this cookbook installation with default httpd installation on same OS


> **Can you also post the apache2 config here rather than a zip please?**

**Overridden properties:**

- node.default['apache']['default_site_port'] = '8080'
- node.default['apache']['listen']            = ['*:8080']
- node.default['apache']['status_url'] = 'http://localhost:8080/server-status'

**Recipe that calls apache2 cookbook**
```
if node[:platform].include?('centos')
  include_recipe 'selinux_policy::install'

  # We need to access node['apache']['listen_ports'] during Chef runtime_phase to catch all ports
  # added during runtime phase, instead of Chef's usual compilation phase evaluation.
  # nesting in a ruby_block resource forces runtime evaluation.
  ruby_block 'Lazy load selinux configuration' do
    block do
      node['apache']['listen_ports'].each do |port|
        selinux_port_resource = Chef::Resource::SelinuxPolicyPort.new(port, run_context)
        selinux_port_resource.protocol 'tcp'
        selinux_port_resource.secontext 'http_port_t'
        selinux_port_resource.run_action(:addormodify)
      end
    end
  end
end

include_recipe 'apache2'

# caching properties is set to false
include_recipe 'apache2::mod_expires' if node['vem']['httpd']['caching']
include_recipe 'apache2::mod_filter'
include_recipe 'apache2::mod_access_compat'
```

I think it might have something to do with module loading mechanism, or mime_module.
When i try to replace some line on generated httpd.conf below

```
# Include module configuration:
IncludeOptional /etc/httpd/mods-enabled/*.load
IncludeOptional /etc/httpd/mods-enabled/*.conf
```

with this line taken from default httpd.conf installed using yum

```
Include conf.modules.d/*.conf

<IfModule mime_module>
    TypesConfig /etc/mime.types

    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz

    AddType text/html .shtml
    AddOutputFilter INCLUDES .shtml
</IfModule>

IncludeOptional conf.d/*.conf
```

the reload action works correctly.

**Comment by lily-liu** [comment] 2018-09-06 05:10
It might be happening because there is some error on mime_module.
When i remove mime_module from default module array, reload action can be executed properly

**Comment by rgriffith** [comment] 2018-10-18 15:08
I am running into similar behavior with an initial bootstrap on an Amazon Linux 2 AMI. The apache2 restart seemingly hangs and I have to abort the bootstrap. 

```
[2018-10-18T14:46:56+00:00] INFO: template[apache2.conf] sending reload action to service[apache2] (delayed)
  * service[apache2] action reload[2018-10-18T14:46:56+00:00] INFO: Processing service[apache2] action reload (apache2::default line 209)
```

Here's what the status of the service looks like at that point:

```
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: reloading (reload) since Thu 2018-10-18 14:46:56 UTC; 8min ago
     Docs: man:httpd.service(8)
  Process: 6025 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, status=0/SUCCESS)
 Main PID: 5992 (httpd)
   Status: "Reading configuration..."
   CGroup: /system.slice/httpd.service
           ├─5992 /usr/sbin/httpd -DFOREGROUND
           ├─6026 /usr/sbin/httpd -DFOREGROUND
           ├─6027 /usr/sbin/httpd -DFOREGROUND
           ├─6028 /usr/sbin/httpd -DFOREGROUND
           ├─6029 /usr/sbin/httpd -DFOREGROUND
           ├─6030 /usr/sbin/httpd -DFOREGROUND
           ├─6031 /usr/sbin/httpd -DFOREGROUND
           ├─6032 /usr/sbin/httpd -DFOREGROUND
           ├─6033 /usr/sbin/httpd -DFOREGROUND
           ├─6034 /usr/sbin/httpd -DFOREGROUND
           ├─6035 /usr/sbin/httpd -DFOREGROUND
           ├─6036 /usr/sbin/httpd -DFOREGROUND
           ├─6037 /usr/sbin/httpd -DFOREGROUND
           ├─6038 /usr/sbin/httpd -DFOREGROUND
           ├─6039 /usr/sbin/httpd -DFOREGROUND
           ├─6040 /usr/sbin/httpd -DFOREGROUND
           └─6041 /usr/sbin/httpd -DFOREGROUND

Oct 18 14:46:56 HOSTNAME systemd[1]: Starting The Apache HTTP Server...
Oct 18 14:46:56 HOSTNAME systemd[1]: Started The Apache HTTP Server.
Oct 18 14:48:26 HOSTNAME systemd[1]: httpd.service reload operation timed out. Stopping.
Oct 18 14:49:57 HOSTNAME systemd[1]: httpd.service reload operation timed out. Stopping.
Oct 18 14:51:27 HOSTNAME systemd[1]: httpd.service reload operation timed out. Stopping.
Oct 18 14:52:57 HOSTNAME systemd[1]: httpd.service reload operation timed out. Stopping.
Oct 18 14:54:27 HOSTNAME systemd[1]: httpd.service reload operation timed out. Stopping.
```

I've also noticed that manually issuing a reload times out, but restart does not.

**Comment by damacus** [comment] 2018-10-18 18:37
Yup, as I suspected this looks very similar to the Fedora bug I encountered

**Comment by damacus** [comment] 2018-10-18 18:40
Quick update. I'm working on getting the definitions moved into custom resources this week or early next week, depending on time allowing, this may allow better control of the reloading/restarting of apache 🤞

**Comment by rgriffith** [comment] 2018-10-19 12:58
I was hoping to use `apache_module 'mime'` in order to avoid the conf file from being created, but it's still being pulled over into `mods-enabled` and preventing the reload.

**Comment by damacus** [comment] 2018-10-19 13:11
Do you include the recipe or use the definition? 

Just for reference, what are you trying to do? I need some background so I can figure out some use cases for the new functionality of `apache2_module`.

**Comment by rgriffith** [comment] 2018-10-19 13:13
I have the following in a wrapper cookbook to install Apache  and a number of modules, but don't need all of the extra `.conf` files:

```
# Set up Apache.
include_recipe 'apache2::default'
apache_module 'authz_core'
apache_module 'deflate'
apache_module 'filter'
apache_module 'log_config'
apache_module 'logio'
apache_module 'mime'
apache_module 'proxy'
apache_module 'proxy_ajp'
apache_module 'proxy_wstunnel'
apache_module 'rewrite'
apache_module 'systemd'
apache_module 'unixd'
# Special case so the package can be installed
include_recipe 'apache2::mod_ssl'
```

I am noticing even without specifying `conf true` (definition sets it to false), it still pulls in the `.conf` file.

**Comment by damacus** [comment] 2018-10-19 13:15
Well that's annoying! 

Right. I have something in the works for this, but it's going to be a short while before it's ready.

**Comment by rgriffith** [comment] 2018-10-19 13:18
I may try throwing in the following to see if I can at least get that `mime.conf` file "disabled" so the reload at least works:

```
apache_config 'mime' do 
  enable false
end
```

**Comment by rgriffith** [comment] 2018-10-19 13:30
We're in the process of switching over from the `httpd` cookbook which  recommends `apache2` and that cookbook doesn't really add much in terms of config files. This is why I was hoping to use `apache_module` to avoid those extra config files being added. 

Similarly, it'd be nice to take advantage of `mod_ssl` for handling the package, but we don't need the config associated with it.

**Comment by damacus** [comment] 2018-10-19 14:10
If you haven't finished switching over yet. I'd recommend waiting to implement it after we've done a 7.0/7.1 release. 

I'm in the middle of making this all work a bit better. Use cases like this a *very* helpful

**Comment by damacus** [comment] 2018-10-19 15:49
That's a good use case. 

I wonder if it's a time when we just ask the user to supply the templating and you tell "us" to turn it off.

**Comment by rgriffith** [comment] 2018-10-19 16:47
The `httpd` cookbook was very similar to what you're providing with the additional variables. I know in our case that would solve the problem. Maybe just a quick check to see if `variables` is passed, otherwise pass in what you have currently?

**Comment by lily-liu** [comment] 2018-10-23 10:11
Hi, @damacus @rgriffith the workaround that i did for this issue is just copying the whole cookbook to my project, and change all reload action to restart action. I don't know if that's a good way to do it (i think its bad idea?) but the restart works just fine without breaking anything, at least in my case.

**Comment by rgriffith** [comment] 2018-10-23 11:52
Based on the code, you _should_ be able to pass `restart true` into the resource to force a restart instead of reload. I think for swapping out modules, a restart makes sense.

**Comment by fernandoaleman** [comment] 2018-10-30 14:36
@lily-liu I was also able to get it working by copying the cookbook and replacing all the `reload` commands to `restart'.

**Comment by fernandoaleman** [comment] 2018-10-30 14:38
@damacus Along with temporarily getting this to work on Amazon Linux 2, based on @lily-liu's suggestion (until the cookbook is fixed), I also found an error installing `mod_ssl` on Amazon Linux 2 and opened up a separate issue #565.

**Comment by damacus** [comment] 2018-11-15 15:30
Hi there!

would you mind trying to replicate this failure on the current master branch of the cookbook?
From what I've seen this is no longer an issue, but if it is please reopen

Thanks,
Dan

**Comment by fernandoaleman** [comment] 2018-11-15 15:32
@damacus Hi Dan, yes I'll test it out and provide feedback.

**Comment by josephholsten** [comment] 2018-11-26 20:20
@lily-liu How's it going reproducing this? Do you need any help? I'll be closing this ticket in a week if you aren't seeing the issue any longer.

**Comment by damacus** [comment] 2018-11-30 08:14
Closing as resolved. Thanks for the update 👍

**Closed** 2018-11-30 08:14 UTC
Labels: Status: Pending Contributor
