### ISSUE TITLE
/usr/lib64/apache2/mod_mpm_prefork.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mrmarbury** [sous-chefs/apache2#364] opened 2015-06-18 13:08 UTC
Hi,

I am using this Cookbook with SLES12. `apache2::default` runs without any error. But afterwards there is no running process. So I try to start apache by hand. 

The start fails with this error:

`httpd2-prefork: Syntax error on line 122 of /etc/apache2/httpd.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/mpm_prefork.load: Cannot load /usr/lib64/apache2/mod_mpm_prefork.so into server: /usr/lib64/apache2/mod_mpm_prefork.so: cannot open shared object file: No such file or directory`

And yes, there is no `mod_mpm_prefork.so` file whatsoever and I cannot find any package that would install it. 

Is there fix for it or did I miss something? Or do I have to skip this cookbook for sles 12? It is working with 11.3 however. But this is no option here.

Thanks for your help,
Stefan

**Comment by ChrisLundquist** [comment] 2015-09-16 22:17
Hey Stefen,
What happens if you remove the file `/etc/apache2/mods-enabled/mpm_prefork.load`?
It looks like mpm_prefork is statically compiled into the package, so it shouldn't need to load a `.so`

**Comment by svanzoest** [comment] 2015-09-16 22:32
We have worked on OpenSUSE 13, but we do not have access to SLES12, so although we would like it work for SLES 12 it is not part of our test kitchen configuration.

**Comment by ChrisLundquist** [comment] 2015-09-16 22:33
https://github.com/schubergphilis/nagios/issues/420#issuecomment-140908480

Someone on Centos is seeing a similar error.

**Comment by svanzoest** [comment] 2015-09-16 22:55
@ChrisLundquist I do not think that nagios#420 is related, that was caused by including an mpm module recipe rather than setting the `apache.mpm` attribute.

**Comment by ChrisLundquist** [comment] 2015-09-16 22:58
It seems to me that they both result in `/etc/apache2/mods-enabled/mpm_prefork.load` trying to load a library that doesn't exist.

In either case, you've been really helpful and pointed us in the right direction on the other issue. Thanks!

**Comment by svanzoest** [comment] 2015-09-16 23:05
@ChrisLundquist this likely has to do with SLES12 specificly

**Comment by mrmarbury** [comment] 2015-12-07 16:29
Oh sorry that I didn't answer. We are currently switching from sles 12 to centos 7. And on Centos 7 your cookbook is working.

**Comment by DStape** [comment] 2016-03-17 15:27
Hi, I'm running into this exact issue with openSUSE 13.2. Has there been any progress towards a fix? Thanks.

**Comment by svanzoest** [comment] 2016-03-18 23:41
@DStape one of the main challenges is that we do not have SUSE in our test-kitchen environment, so we do not know what the apache2 binary on that platform is like. 

We will gladly accept a PR, as long as we do not break any of the other platforms.

**Comment by coldoch** [comment] 2016-05-13 11:01
@svanzoest I've no idea how this stuff works, but for opensuse 13.2, the problem is resolved by removing the mpm_prefork.load, as the module doesn't exist, I believe because it is compiled in. Is there a way to prevent this .load getting generated. I've had a look at the script, apache2_module_conf_generate.pl, but I'm not sure where it is getting its source?

**Comment by krues8dr** [comment] 2016-08-02 13:28
FWIW, I'm seeing this same issue on CentOS 6.7 and 6.8.

**Comment by svanzoest** [comment] 2016-11-07 00:58
looks like opensuse has its default mpm as `prefork`:
```
kitchen login default-opensuse-132
vagrant@default-opensuse-132:~> sudo -i
default-opensuse-132:~ # apache2ctl  -V
Server version: Apache/2.4.10 (Linux/SUSE)
Server built:   2016-07-18 16:42:09.000000000 +0000
Server's Module Magic Number: 20120211:36
Server loaded:  APR 1.5.1, APR-UTIL 1.5.3
Compiled using: APR 1.5.1, APR-UTIL 1.5.3
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_PROC_PTHREAD_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/srv/www"
 -D SUEXEC_BIN="/usr/sbin/suexec2"
 -D DEFAULT_PIDLOG="/run/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="/var/log/apache2/error_log"
 -D AP_TYPES_CONFIG_FILE="/etc/apache2/mime.types"
 -D SERVER_CONFIG_FILE="/etc/apache2/httpd.conf"
```

**Comment by damacus** [comment] 2018-07-31 09:13
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Closed by damacus** 2018-07-31 09:13 UTC
Labels: enhancement, os/suse
