### ISSUE TITLE
Apache restart triggered by mpm_prefork fails

### ISSUE THREAD

**Issue by phpPhil** [sous-chefs/apache2#355] opened 2015-05-11 12:09 UTC
I just came across an issue which is possibly related to other mpm issues I read about on this tracker, especially #333 and #354.

When setting `mpm => prefork` apache fails to restart itself after `a2enmod mpm_prefork`. 
Interesting is there's nothing in stdout and stderr that could indicate what actually went wrong, this is the output:

```
    ==> my-server: [2015-05-10T12:05:25+10:00] INFO: execute[a2enmod mpm_prefork] sending restart action to service[apache2] (delayed)
    ==> my-server: [2015-05-10T12:05:25+10:00] INFO: Processing service[apache2] action restart (apache2::default line 202)
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] supports status, running
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] is running
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 0, action stop, priority 09
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 1, action stop, priority 09
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 2, action start, priority 91
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 3, action start, priority 91
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 4, action start, priority 91
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 5, action start, priority 91
    ==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 6, action stop, priority 09
    ==> my-server: ================================================================================
    ==> my-server: Error executing action `restart` on resource 'service[apache2]'
    ==> my-server: ================================================================================
    ==> my-server: Mixlib::ShellOut::ShellCommandFailed
    ==> my-server: ------------------------------------
    ==> my-server: Expected process to exit with [0], but received '1'
    ==> my-server: ---- Begin output of /etc/init.d/apache2 restart ----
    ==> my-server: STDOUT: * Restarting web server apache2
    ==> my-server:    ...fail!
    ==> my-server: STDERR: 
    ==> my-server: ---- End output of /etc/init.d/apache2 restart ----
    ==> my-server: Ran /etc/init.d/apache2 restart returned 1
    ==> my-server: Resource Declaration:
    ==> my-server: ---------------------
    ==> my-server: # In /tmp/vagrant-chef-2/chef-solo-1/cookbooks/apache2/recipes/default.rb
    ==> my-server: 202: service 'apache2' do
    ==> my-server: 203:   service_name node['apache']['service_name']
    ==> my-server: 204:   case node['platform_family']
    ==> my-server: 205:   when 'rhel'
    ==> my-server: 206:     reload_command '/sbin/service httpd graceful'
    ==> my-server: 207:   when 'debian'
    ==> my-server: 208:     provider Chef::Provider::Service::Debian
    ==> my-server: 209:   when 'arch'
    ==> my-server: 210:     service_name 'httpd'
    ==> my-server: 211:   end
    ==> my-server: 212:   supports [:start, :restart, :reload, :status]
    ==> my-server: Compiled Resource:
    ==> my-server: ------------------
    ==> my-server: # Declared in /tmp/vagrant-chef-2/chef-solo-1/cookbooks/apache2/recipes/default.rb:202:in `from_file'
    ==> my-server: service("apache2") do
    ==> my-server:   provider Chef::Provider::Service::Debian
    ==> my-server:   action [:enable, :start]
    ==> my-server:   updated true
    ==> my-server:   supports {:restart=>true, :reload=>true, :status=>true, :start=>true}
    ==> my-server:   retries 0
    ==> my-server:   retry_delay 2
    ==> my-server:   default_guard_interpreter :default
    ==> my-server:   service_name "apache2"
    ==> my-server:   enabled true
    ==> my-server:   running true
    ==> my-server:   pattern "apache2"
    ==> my-server:   declared_type :service
    ==> my-server:   cookbook_name :apache2
    ==> my-server:   recipe_name "default"
    ==> my-server:   only_if "/usr/sbin/apache2 -t"
    ==> my-server: end
```

These are the Apache logs:

```
[Sun May 10 12:05:25.751435 2015] [mpm_prefork:notice] [pid 22189] AH00171: Graceful restart requested, doing restart
[Sun May 10 12:05:25.984364 2015] [ssl:warn] [pid 22189] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun May 10 12:05:25.996166 2015] [mpm_prefork:notice] [pid 22189] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.9 OpenSSL/1.0.1f configured -- resuming normal operations
[Sun May 10 12:05:25.996183 2015] [core:notice] [pid 22189] AH00094: Command line: '/usr/sbin/apache2'
```

Worth noting...
- When I log into the machine after the process aborts, I can restart Apache without any issues.
- This is on AWS, I'm using the Ubuntu AMI `ami-d05e75b8`
- I'm running Apache/2.4.7 (Ubuntu)

The error stops the provisioning half way through. 
Is there any workaround for this?

**Comment by svanzoest** [comment] 2015-05-25 00:17
How are you setting `apache.mpm` to `prefork`? It is expected that you set this attribute before the `apache2` recipes run.

**Comment by phpPhil** [comment] 2015-05-26 23:09
I'm using chef solo to provision. I configure the setting via chef.json:

    chef.json = {
        ...
        :apache => {
            :mpm => 'prefork'
        },
        ...
    }

So yes, this is configured before the apache2 recipes run.

**Comment by sergiuionescu** [comment] 2015-06-21 06:53
I get the same issue with an ubuntu 14.04 vagrant box, apache configured with prefork.

**Comment by miketheman** [comment] 2015-08-09 12:30
I've been digging further into this issue, in hopes of resolving it.

I have been able to reproduce this outside of a Chef run on the running instance by issuing a reload before the restart and seeing the same behavior.
This is commonly seen on a fresh node's startup, as there are many resources which will notify the service to `:reload` and then finally `:restart`.

This is basically: `service apache2 reload && service apache2 restart` - which also fails, whereas the restart only works just fine.

On a "vanilla" install of a node with `apt-get install apache2

**Comment by miketheman** [comment] 2015-08-09 13:18
I also can't help but wonder how apache behaves when the worker module has changed out from under it and a `reload` is issued - from the CLI output on `a2enmod mpm_*`, we are warned to restart apache.

```shellsession
root@ea1f9167be80:/# a2dismod mpm_event
Module mpm_event disabled.
To activate the new configuration, you need to run:
  service apache2 restart
root@ea1f9167be80:/# a2enmod mpm_prefork
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Considering conflict mpm_itk for mpm_prefork:
Enabling module mpm_prefork.
To activate the new configuration, you need to run:
  service apache2 restart
```

If a reload happens in between replacing the mpm type and a regular restart, you may end up with apache stopped, and this error shows up in error.log:
`AH00534: apache2: Configuration error: The MPM cannot be changed during restart.`

On a fresh, new Ubuntu 14.04 with `apt-get install apache2`, running

`a2dismod mpm_worker && a2enmod mpm_prefork && service apache2 reload`

results in a stopped apache process, but `service apache2 restart` brings it back online without failure.

Which brings me back to maybe there's some delay in the loaded modules slowing down the graceful reload exiting, and the restart starting, as it finds the running pid and issues an `apachectl stop` and then waits 60 seconds to see if it stopped, then fails.

**Comment by martinb3** [comment] 2015-08-09 19:40
Hmmm. What a mess. It seems like maybe possible options are:

- don't reload if a restart is pending
- extend the service provider and add a sleep, e.g. [varnish_log](https://github.com/rackspace-cookbooks/varnish/blob/master/libraries/varnish_log.rb#L26-L59)
- do an immediate restart if an mpm is changed

**Comment by billclark91** [comment] 2015-10-31 17:28
I too am experiencing this issue on Ubuntu 14.04 when mpm_prefork is enabled with recipe.  As @miketheman has pointed out, `service apache2 reload && service apache2 restart` hangs at command line while `service apache2 reload && sleep 1 && service apache2 restart` succeeds.

Stealing a page from the Tomcat recipe, I would like to propose a 'wait for apache2' execution which sleeps 2.

apache2/recipes/default.rb, line 209

```
service 'apache2' do
  service_name apache_service_name
  case node['platform_family']
  when 'rhel'
    restart_command "/sbin/service #{apache_service_name} restart && sleep 1" if node['apache']['version'] == '2.2'
    reload_command "/sbin/service #{apache_service_name} graceful"
  when 'debian'
    provider Chef::Provider::Service::Debian
  when 'arch'
    service_name apache_service_name
  end
  supports [:start, :restart, :reload, :status]
  action [:enable, :start]
  notifies :run, 'execute[wait for apache2]', :immediately
  only_if "#{node['apache']['binary']} -t", :environment => { 'APACHE_LOG_DIR' => node['apache']['log_dir'] }, :timeout => 10
end

execute 'wait for apache2' do
  command 'sleep 2'
  action :nothing
end
```

I have tested this modification on Ubuntu 14.04 and deployments no longer fail.

**Comment by miketheman** [comment] 2015-11-14 23:07
@martinb3 I think the two options that make most sense are:
- don't reload if a restart is pending
- extend the service provider and add a sleep

The second option seems to be reasonable from the solution posted by @billclark91 above, but I agree the first option of preventing a reload if a restart is pending makes most sense.

I'm not certain how simple that is - i.e. reaching back in to the resource collection at the end of the run, but before the action is taken, and determining if there's a restart to be done and removing any reload.

So I'd be a :+1: on a `sleep` for the short term, at least until the longer term fix could be sorted out.

**Comment by ezekg** [comment] 2016-07-26 15:30
Any update on this? I've been randomly hitting this issue as well. Is there a patch that can be easily implemented in the time being?

**Comment by rossedman** [comment] 2016-08-24 15:54
I am experiencing this as well. The most I can discover is that this cookbook destroys the `root` apache process. When restarting or installing if you run:

Here is an example in a failing state:

```
$ fuser -v 80/tcp

80/tcp:         apache     2277 F.... httpd
                     apache     2278 F.... httpd
                     apache     2279 F.... httpd
                     apache     2280 F.... httpd
                     apache     2281 F.... httpd
                     apache     2282 F.... httpd
                     apache     2283 F.... httpd
                     apache     2284 F.... httpd
                     apache     2285 F.... httpd
                     apache     2286 F.... httpd
                     apache     2287 F.... httpd
                     apache     2288 F.... httpd
                     apache     2289 F.... httpd
                     apache     2290 F.... httpd
                     apache     2291 F.... httpd
                     apache     2292 F.... httpd
```

And if I run these command, apache will then restart, notice the top level root process:

```
$ fuser -k 80/tcp
$ service httpd restart
$ fuser -v 80/tcp

80/tcp:         root          2480 F.... httpd
                     apache     2482 F.... httpd
                     apache     2483 F.... httpd
                     apache     2484 F.... httpd
                     apache     2485 F.... httpd
                     apache     2486 F.... httpd
                     apache     2487 F.... httpd
                     apache     2488 F.... httpd
                     apache     2489 F.... httpd
                     apache     2490 F.... httpd
                     apache     2491 F.... httpd
                     apache     2492 F.... httpd
                     apache     2493 F.... httpd
                     apache     2494 F.... httpd
                     apache     2495 F.... httpd
                     apache     2496 F.... httpd
                     apache     2497 F.... httpd
                     apache     2506 F.... httpd
                     apache     2507 F.... httpd
                     apache     2508 F.... httpd
```

**Comment by damacus** [comment] 2018-11-15 15:10
Hi there! 

can you see if this is still a case on the current version of master. 

Closing as this is a very old ticket

**Closed by damacus** 2018-11-15 15:10 UTC
Labels: apache/2.4, bug, os/ubuntu
